version: '3.8'

# From: https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee

services:
  db-mysql:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      # Username and pwd for non-root user
      MYSQL_USER: 'exampleUser'
      MYSQL_PASSWORD: 'pwd12345'

      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword' 
    ports:
      - '4040:4040'
    networks:
      - backend-net
    volumes:
      - db-data:/var/lib/mysql

networks:
  backend-net:
    driver: bridge

volumes:
  db-data: