version: '3.8'

# From: 
# - https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
# - https://iamvickyav.medium.com/mysql-init-script-on-docker-compose-e53677102e48

services:
  mysql:
    image: mysql
    container_name: mysql-db
    environment:
      #! NOTE: Have to create db name here for user to have access to db
      MYSQL_DATABASE: manga_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    networks:
      - backnet
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql

networks:
  backnet:
    driver: bridge

volumes:
  mysql-data:
    driver: local
